version: '3.8'

services:
  web:
    build: .
    ports:
      - "3030:5000"
    volumes:
      - .:/app:rw
      - files:/app/files
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

volumes:
  files:
